### ISSUE TITLE
大飞哥怎么在学clj和scala？

### ISSUE THREAD

**Issue by jasper-zhang** [redsnow1992/notes#2]
大飞哥怎么在学clj和scala？偏爱这些冷门语言啊？

**Comment by redsnow1992** [comment]
头儿说让我们做好学scala的准备，ruby效率有些不太好，援引了twitter的例子（从ruby转到scala）。
看了几天scala觉得语法相当复杂，倒是挺喜欢clojure的（以前学过lisp系的语言）。希望借着这些jvm上的语言来把线程，并发理解好。

**Comment by jasper-zhang** [comment]
好吧，这语言更新太快了，最近我也在开始看go了。你想理解线程并发直接学java不就好了。
